### PR TITLE
Update WWX.gst

### PR DESCRIPTION
**Pull request by nwilson1225**
Added rest of Outlaw bosses
Added some faces
Stubbed all merc face profiles

### CODE REVIEW

**Comment by Drizzt-IT** [comment]
Hey, Why do you add everything in the main file and not in the outlaw one?

**Comment by Drizzt-IT** [comment]
Please change that and putt everything regarding the outlaws into into the outlaw file.

**Comment by Drizzt-IT** [comment]
Other wise you can see the outlaws any every other file. To have the rules in the main file is great. Then we can update faster later on...

**Comment by nwilson1225** [comment]
The idea was that most of the outlaws can be used by other factions.  I think it would be best to avoid copy pasting the same faces in multiple files (so when they get errata'd you don't have to edit every file.  I can do some refactoring though.  I'm still experimenting with how to make posse building work

**Comment by nwilson1225** [comment]
I actually closed this because at some point my roster stopped opening, still trying to figure it out.  Also going to be on vacation for 2 weeks soon and was trying to get the rules in.  If you want to move the outlaws I committed that's fine

**Comment by Drizzt-IT** [comment]
> The idea was that most of the outlaws can be used by other factions. I think it would be best to avoid copy pasting the same faces in multiple files (so when they get errata'd you don't have to edit every file. I can do some refactoring though. I'm still experimenting with how to make posse building work

Yeah that would be very nice. Otherwise everything gets pretty full

**Pull request closed without merging**
